# Generated by Django 4.0.2 on 2022-05-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geolocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Latitude', models.IntegerField(max_length=10)),
                ('Longitude', models.IntegerField(max_length=10)),
            ],
        ),
    ]
