# Generated by Django 4.0.2 on 2022-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='Latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='Longitude',
            field=models.IntegerField(),
        ),
    ]
